/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.okstate.frames;

import edu.okstate.entities.ProjectDataFull;
import edu.okstate.executables.ExportProject;
import edu.okstate.executables.IntegrationTemplate;
import edu.okstate.executables.ProjectSearch;
import edu.okstate.executables.SelectProject;
import edu.okstate.executables.UpdateProjectHeader;
import edu.okstate.executables.CopyFullRecord;
import edu.okstate.executables.DeleteCompleteRecord;
import edu.okstate.executables.GetProjectData;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.*;
import javax.swing.*;

import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

/**
 *
 * @author CIVE Administrator
 */
@SuppressWarnings("serial")
public class PrHeaderFrame extends javax.swing.JFrame {

    private int projectHeaderID;
    @SuppressWarnings("unused")
	private Object Jlist2;
    List<ProjectDataFull> projectDataFull;
    //MODEL
    @SuppressWarnings("rawtypes")
	DefaultListModel templatesModel = new DefaultListModel();

    /**
     * Creates new form WelFrame
     */
    public PrHeaderFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\CPM-Software\\src\\main\\resources\\odot.png"));
    }

    public PrHeaderFrame(int projectHeaderID) {
        this.projectHeaderID = projectHeaderID;
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\CPM-Software\\src\\main\\resources\\odot.png"));
    }

    @SuppressWarnings("unchecked")
	private void add(String name) {

        projectDescriptionList.setModel(templatesModel);
        projectDescriptionList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        templatesModel.addElement(name);
    }

    private void addElementsToTemplateList() {

        templatesModel.clear();
        ArrayList<String> templateNames = new ArrayList<String>();

        templateNames = IntegrationTemplate.returnTempalteHeaders(2);
        for (String name : templateNames)
        	add(name);
    }

    private void addElementsToProjectsList(String a, String b, String c, String d, String e, String f, String g, String h, String i) {

        templatesModel.clear();
        ArrayList<String> templateNames = new ArrayList<String>();

        templateNames = ProjectSearch.returnTempalteHeaders(a, b, c, d, e, f, g, h, i);

        for (String name : templateNames) {
            add(name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        searchProject = new javax.swing.JButton();
        listAllProjects = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectDescriptionList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        copyButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        detailsButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OK_CTDS 2.0");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 400));
        jPanel1.setName("Project Details"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 465));

        jLabel1.setText("                 Project Description");

        jLabel2.setText("          County");

        jLabel3.setText("          Project#");

        jLabel4.setText("          Job Piece#");

        jLabel5.setText("          Highway#");

        jLabel6.setText("                 Project Engineer/Contact");

        jLabel7.setText("          Letting Date (YYYY-MM-DD)");

        jLabel8.setText("          Reference Marks");

        jLabel9.setText("          STA to STA");

        jTextField1.setMaximumSize(new java.awt.Dimension(300, 39));
        jTextField1.setMinimumSize(new java.awt.Dimension(300, 39));
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 39));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setMaximumSize(new java.awt.Dimension(300, 39));
        jTextField2.setMinimumSize(new java.awt.Dimension(300, 39));
        jTextField2.setPreferredSize(new java.awt.Dimension(300, 39));

        jTextField3.setMaximumSize(new java.awt.Dimension(300, 39));
        jTextField3.setMinimumSize(new java.awt.Dimension(300, 39));
        jTextField3.setPreferredSize(new java.awt.Dimension(300, 39));

        jTextField4.setMaximumSize(new java.awt.Dimension(300, 39));
        jTextField4.setMinimumSize(new java.awt.Dimension(300, 39));
        jTextField4.setPreferredSize(new java.awt.Dimension(300, 39));

        jTextField5.setMaximumSize(new java.awt.Dimension(300, 39));
        jTextField5.setMinimumSize(new java.awt.Dimension(300, 39));
        jTextField5.setPreferredSize(new java.awt.Dimension(300, 39));

        jTextField6.setMaximumSize(new java.awt.Dimension(300, 39));
        jTextField6.setMinimumSize(new java.awt.Dimension(300, 39));
        jTextField6.setPreferredSize(new java.awt.Dimension(300, 39));

        jTextField7.setMaximumSize(new java.awt.Dimension(300, 39));
        jTextField7.setMinimumSize(new java.awt.Dimension(300, 39));
        jTextField7.setPreferredSize(new java.awt.Dimension(300, 39));

        jTextField8.setMaximumSize(new java.awt.Dimension(300, 39));
        jTextField8.setMinimumSize(new java.awt.Dimension(300, 39));
        jTextField8.setPreferredSize(new java.awt.Dimension(300, 39));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setMaximumSize(new java.awt.Dimension(300, 39));
        jTextField9.setMinimumSize(new java.awt.Dimension(300, 39));
        jTextField9.setPreferredSize(new java.awt.Dimension(300, 39));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 190));

        searchProject.setText("Search Project");
        searchProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchProject.setMaximumSize(new java.awt.Dimension(244, 41));
        searchProject.setMinimumSize(new java.awt.Dimension(244, 41));
        searchProject.setPreferredSize(new java.awt.Dimension(244, 41));
        searchProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProjectActionPerformed(evt);
            }
        });

        listAllProjects.setText("List All Projects");
        listAllProjects.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listAllProjects.setMaximumSize(new java.awt.Dimension(244, 41));
        listAllProjects.setMinimumSize(new java.awt.Dimension(244, 41));
        listAllProjects.setPreferredSize(new java.awt.Dimension(244, 41));
        listAllProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllProjectsActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(109, 41));
        jButton3.setMinimumSize(new java.awt.Dimension(109, 41));
        jButton3.setPreferredSize(new java.awt.Dimension(109, 41));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clearButton.setMaximumSize(new java.awt.Dimension(109, 41));
        clearButton.setMinimumSize(new java.awt.Dimension(109, 41));
        clearButton.setPreferredSize(new java.awt.Dimension(109, 41));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listAllProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchProject, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listAllProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 400));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 465));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setVerifyInputWhenFocusTarget(false);

        jScrollPane2.setViewportView(projectDescriptionList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 190));

        jButton4.setText("Select Project");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(300, 41));
        jButton4.setMinimumSize(new java.awt.Dimension(300, 41));
        jButton4.setPreferredSize(new java.awt.Dimension(300, 41));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        saveButton.setText("Save Project");
        saveButton.setEnabled(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setMaximumSize(new java.awt.Dimension(132, 41));
        saveButton.setMinimumSize(new java.awt.Dimension(132, 41));
        saveButton.setPreferredSize(new java.awt.Dimension(132, 41));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        copyButton.setText("Make A Copy");
        copyButton.setEnabled(false);
        copyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyButton.setMaximumSize(new java.awt.Dimension(132, 41));
        copyButton.setMinimumSize(new java.awt.Dimension(132, 41));
        copyButton.setPreferredSize(new java.awt.Dimension(132, 41));
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        jButton7.setText("New Project");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMaximumSize(new java.awt.Dimension(290, 41));
        jButton7.setMinimumSize(new java.awt.Dimension(290, 41));
        jButton7.setPreferredSize(new java.awt.Dimension(290, 41));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(copyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 190));

        detailsButton.setText("View Project Details");
        detailsButton.setEnabled(false);
        detailsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        detailsButton.setMaximumSize(new java.awt.Dimension(244, 41));
        detailsButton.setMinimumSize(new java.awt.Dimension(244, 41));
        detailsButton.setPreferredSize(new java.awt.Dimension(244, 41));
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });

        exportButton.setText("Export Project");
        exportButton.setEnabled(false);
        exportButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportButton.setMaximumSize(new java.awt.Dimension(244, 41));
        exportButton.setMinimumSize(new java.awt.Dimension(244, 41));
        exportButton.setPreferredSize(new java.awt.Dimension(244, 41));
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					exportButtonActionPerformed(evt);
				} catch (FileNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (InvalidFormatException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        deleteButton.setText("Delete Project");
        deleteButton.setEnabled(false);
        deleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteButton.setMaximumSize(new java.awt.Dimension(244, 41));
        deleteButton.setMinimumSize(new java.awt.Dimension(244, 41));
        deleteButton.setPreferredSize(new java.awt.Dimension(244, 41));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
            // TODO add your handling code here:
	}                                           
    private javax.swing.JFrame frame;

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            // TODO add your handling code here:
            frame = new JFrame("EXIT");

            if (JOptionPane.showConfirmDialog(frame, "Confirm EXIT?", "EXIT", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                System.exit(0);
            }
	}                                        

	private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
            // TODO add your handling code here:
            saveButton.setEnabled(false);
            copyButton.setEnabled(false);
            exportButton.setEnabled(false);
            deleteButton.setEnabled(false);
            clearAllFields();
            templatesModel.clear();
	}                                           

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            // TODO add your handling code here:
            //TemplateChoice toTemplate = new TemplateChoice();
            //toTemplate.setVisible(true);
            //setDefaultAllFields();
            TemplateChoice.pain();
            clearAllFields();
            templatesModel.clear();
            saveButton.setEnabled(false);
            copyButton.setEnabled(false);
            deleteButton.setEnabled(false);
	}                                        

	private void listAllProjectsActionPerformed(java.awt.event.ActionEvent evt) {                                                
            clearAllFields();
            try {
                addElementsToTemplateList();
            } catch (java.lang.IndexOutOfBoundsException e) {
                javax.swing.JFrame frame;
                frame = new JFrame("Information");
                JOptionPane.showMessageDialog(frame, "Are you ready to create the 1st record?", "No Records Available", JOptionPane.PLAIN_MESSAGE);
            }
	}                                               

	private void searchProjectActionPerformed(java.awt.event.ActionEvent evt) {                                              
            // TODO add your handling code here:
            addElementsToProjectsList(
                    jTextField1.getText(),
                    jTextField2.getText(),
                    jTextField3.getText(),
                    jTextField4.getText(),
                    jTextField5.getText(),
                    jTextField6.getText(),
                    jTextField7.getText(),
                    jTextField8.getText(),
                    jTextField9.getText());
	}                                             

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            // TODO add your handling code here:
            try {
                String selected = (String) projectDescriptionList.getSelectedValue();

                ArrayList<String> projectHeaderDetails = new ArrayList<String>();

                projectHeaderDetails = SelectProject.returnHeaderDetails(selected);

                jTextField1.setText(projectHeaderDetails.get(0));
                jTextField2.setText(projectHeaderDetails.get(1));
                jTextField3.setText(projectHeaderDetails.get(2));
                jTextField4.setText(projectHeaderDetails.get(3));
                jTextField5.setText(projectHeaderDetails.get(4));
                jTextField6.setText(projectHeaderDetails.get(5));
                jTextField7.setText(projectHeaderDetails.get(6));
                jTextField8.setText(projectHeaderDetails.get(7));
                jTextField9.setText(projectHeaderDetails.get(8));
                //String s = (String) jList2.getSelectedValue();
                //parser(index);
                //copyButton.setEnabled(true);
                detailsButton.setEnabled(true);
                saveButton.setEnabled(true);
                copyButton.setEnabled(true);
                deleteButton.setEnabled(true);
            } catch (IndexOutOfBoundsException e) {
                javax.swing.JFrame frame;
                frame = new JFrame("Warning");
                JOptionPane.showMessageDialog(frame, "Please select a record from the list", "NO SELECTION", JOptionPane.WARNING_MESSAGE);
            }
            exportButton.setEnabled(true);
	}                                        

	private void detailsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
            // TODO add your handling code here:
            ProjectDetails.toProjectDetailsFrame((String) projectDescriptionList.getSelectedValue());
            exportButton.setEnabled(true);
	}                                             

    public void catchProjectId(int id) {

        System.out.println("************************************************ cought id:" + id);

        this.projectHeaderID = id;

        System.out.println("************************************************ assigned to projectHeaderID:" + projectHeaderID);
    }
	private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
            // TODO add your handling code here:
            System.out.println("projectHeaderID in save buttonnnnnnnnnnnnnnnnnnnnnnnnnnnnn" + this.getProjectHeaderID());
            if (jTextField1.getText().contains("Project_Description_")) {

                javax.swing.JFrame frame;
                frame = new JFrame("Warning");
                JOptionPane.showMessageDialog(frame, "Please change the Project Description entry\nNote: Project_Description_XX not allowed for manual update", "INVALID ENTRY", JOptionPane.WARNING_MESSAGE);
                saveButton.setEnabled(false);
                copyButton.setEnabled(false);
                deleteButton.setEnabled(false);
            } else {
                UpdateProjectHeader.updateProjectHeader((String) projectDescriptionList.getSelectedValue(), jTextField1.getText(), jTextField2.getText(), jTextField3.getText(), jTextField4.getText(), jTextField5.getText(), jTextField6.getText(), jTextField7.getText(), jTextField8.getText(), jTextField9.getText());
                saveButton.setEnabled(false);
                copyButton.setEnabled(false);
                deleteButton.setEnabled(false);
            }
            templatesModel.clear();
            clearAllFields();
            try {
                addElementsToTemplateList();
            } catch (java.lang.IndexOutOfBoundsException e) {
                javax.swing.JFrame frame;
                frame = new JFrame("Information");
                JOptionPane.showMessageDialog(frame, "Are you ready to create the 1st record?", "No Records Available", JOptionPane.PLAIN_MESSAGE);
            }
	}                                          

	private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
            // TODO add your handling code here:
            String selected = (String) projectDescriptionList.getSelectedValue();
            CopyFullRecord.copyFullRecord(selected);

            saveButton.setEnabled(false);
            copyButton.setEnabled(false);
            deleteButton.setEnabled(false);
	}                                          

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException, IOException, InvalidFormatException, InterruptedException {                                             
        // TODO add your handling code here:
    	deleteButton.setEnabled(false);
        String selected = (String) projectDescriptionList.getSelectedValue();
        projectDataFull = GetProjectData.getProjectData(selected);
        int gotId = projectDataFull.get(0).getCompound().getProHeaderDataId().getId();
        String excelFilePath = ExportProject.goToExport(gotId, selected);
        exportButton.setEnabled(false);
        javax.swing.JFrame frame;
        frame = new JFrame("Information");
        //JOptionPane.showMessageDialog(frame, "EXPORTED successfully!\nContinue to Microsoft Project?", "Success!", JOptionPane.INFORMATION_MESSAGE);
        
        
        if (JOptionPane.showConfirmDialog(frame, "EXPORTED successfully!\nContinue to Microsoft Project?", "Success!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
        	Thread.sleep(2000);
            try {
            	Runtime.getRuntime().exec( "wscript C:\\Users\\apampan\\git\\ODOT-Software\\ODOT-Software\\target\\classes\\edu\\okstate\\executables\\program.vbs " + excelFilePath);
            	//C:\Users\apampan\git\ODOT-Software\ODOT-Software
            }catch(Exception e){
            	e.printStackTrace();
            }
        }else {
        	File file = new File(excelFilePath);
        	if(file.delete())
        		System.out.println("File Deleted Successfully!");
        	else
        		System.out.println("Couldn't Delete the file...");
        }
    }                                            

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        frame = new JFrame("EXIT");

        if (JOptionPane.showConfirmDialog(frame, "Confirm DELETE?", "DELETE", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            String selected = (String) projectDescriptionList.getSelectedValue();
            DeleteCompleteRecord.deleteCompleteRecord(selected);
            saveButton.setEnabled(false);
            deleteButton.setEnabled(false);
            copyButton.setEnabled(false);
            clearAllFields();
            templatesModel.clear();
            javax.swing.JFrame frame;
            frame = new JFrame("Information");
            JOptionPane.showMessageDialog(frame, "DELETED successfully!", "Success!", JOptionPane.INFORMATION_MESSAGE);
        }

    }                                            

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void prHeaderMain() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrHeaderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrHeaderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrHeaderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrHeaderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrHeaderFrame().setVisible(true);
            }
        });
    }

    public void setDefaultAllFields(String description, String county, String project, String job, String highway, String contact, String date, String ref, String sta) {
        //setDefault(description);
        System.out.println("-------Welcome frame 1-----------");
        jTextField1.setText("description");
        System.out.println("Desription recieved is:" + description);
        jTextField2.setText(county);
        jTextField3.setText(project);
        jTextField4.setText(job);
        System.out.println("-------Welcome frame 2-----------");
        jTextField5.setText(highway);
        jTextField6.setText(contact);
        jTextField7.setText(date);
        jTextField8.setText(ref);
        jTextField9.setText(sta);
    }

    public void setDefault(String prasad) {
        jTextField1.setText(prasad);
        jTextField2.setText("Default");
        jTextField3.setText("Default");
        jTextField4.setText("Default");
        jTextField5.setText("Default");
        jTextField6.setText("Default");
        jTextField7.setText("2007-01-01");
        jTextField8.setText("Default");
        jTextField9.setText("Default");
    }

    public void clearAllFields() {
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
    }

    public int getProjectHeaderID() {
        return projectHeaderID;
    }

    public void setProjectHeaderID(int projectHeaderID) {
        this.projectHeaderID = projectHeaderID;
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton clearButton;
    private javax.swing.JButton copyButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton detailsButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton listAllProjects;
    private javax.swing.JList projectDescriptionList;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchProject;
    // End of variables declaration                   
}
